# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MTDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'MessageThrottle', :path => '../', :subspecs => ['MTCore']
  # Pods for MTDemo

  target 'MTDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MTDemoUITests' do
    # Pods for testing
  end

end
